# Generated by Django 3.2.3 on 2021-05-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tagname_tags'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tags',
            constraint=models.UniqueConstraint(fields=('memo', 'tag'), name='tags_unique'),
        ),
    ]
